#!/usr/bin/env bash

OPT=${1?Error: no option given}
BBSWITCH=/etc/modules-load.d/bbswitch.conf

if [ "$OPT" = "status" ]; then
    if [ -e "$BBSWITCH" ]; then
        echo "Intel is on"
    else
        echo "NVIDIA is on"
    fi
fi

if [ "$OPT" = "intel" ]; then
    echo "Turning off NVIDIA dGPU..."
    echo "Setting bbswith to start on boot..."
    sudo cp bbswitch-load.conf /etc/modules-load.d/bbswitch.conf
    sudo cp bbswitch.conf /etc/modprobe.d/bbswitch.conf
    echo "Blacklist any NVIDIA drivers..."
    sudo cp simpleswitch.conf /etc/modprobe.d/simpleswitch.conf
    echo "Removing NVIDIA Optimus X.ORG config"
    sudo rm /etc/X11/xorg.conf
    echo "Removing GDM Optimus config"
    sudo rm /usr/share/gdm/greeter/autostart/optimus.desktop
    sudo rm /etc/xdg/autostart/optimus.desktop
    echo "Setting up GRUB Kernel Paramenters..."
    sudo cp grub-intel /etc/default/grub
    sudo grub-mkconfig -o /boot/grub/grub.cfg
    echo "Setting up Initramfs..."
    sudo cp mkinit-intel.conf /etc/mkinitcpio.conf
    sudo mkinitcpio -p linux
    echo "Intel Graphics ready to go. Please restart your system"
fi

if [ "$OPT" = "nvidia" ]; then
    echo "Turning on NVIDIA dGPU..."
    echo "Removing bbswitch from boot..."
    sudo rm /etc/modules-load.d/bbswitch.conf
    sudo rm /etc/modprobe.d/bbswitch.conf
    echo "Enabling NVIDIA driver..."
    sudo rm /etc/modprobe.d/simpleswitch.conf
    echo "Setting up NVIDIA Optimus X.ORG config"
    sudo cp nvidia-xorg.conf /etc/X11/xorg.conf
    echo "Setting up GDM Optimus config"
    sudo cp gdm-config.desktop /usr/share/gdm/greeter/autostart/optimus.desktop
    sudo cp gdm-config.desktop /etc/xdg/autostart/optimus.desktop
    echo "Setting up GRUB Kernel Paramenters..."
    sudo cp grub-nvidia /etc/default/grub
    sudo grub-mkconfig -o /boot/grub/grub.cfg
    echo "Setting up Initramfs..."
    sudo cp mkinit-nvidia.conf /etc/mkinitcpio.conf
    sudo mkinitcpio -p linux
    echo "Nvidia dGPU ready to go. Please restart your system"
fi
