#!/usr/bin/env bash

OPT=${1?Error: no option given}
BBSWITCH=/etc/modules-load.d/bbswitch.conf

if [ "$OPT" = "status" ]; then
    if [ -e "$BBSWITCH" ]; then
        echo "Intel is on"
    else
        echo "NVIDIA is on"
    fi
fi

if [ "$OPT" = "help" ]; then
	echo ""
	echo "  options:"
	echo "    help"
	echo "    block_nvidia"
	echo "    enable_nvidia"
	echo ""
fi

if [ "$OPT" = "block_nvidia" ]; then
    echo "Turning off NVIDIA dGPU..."
    echo "Setting bbswith to start on boot..."
    sudo cp bbswitch-load.conf /etc/modules-load.d/bbswitch.conf
    sudo cp bbswitch.conf /etc/modprobe.d/bbswitch.conf
    echo "Blacklist any NVIDIA drivers..."
    sudo cp simpleswitch.conf /etc/modprobe.d/simpleswitch.conf
    echo "Nvidia card will turn off after next reboot"
fi

if [ "$OPT" = "enable_nvidia" ]; then
    echo "Removing bbswitch to start on boot"
    sudo rm /etc/modules-load.d/bbswitch.conf 
    sudo rm /etc/modprobe.d/bbswitch.conf
    echo "Enabling NVIDIA drivers"
    sudo rm /etc/modprobe.d/simpleswitch.conf
    echo "Nvidia dGPU will be on after next reboot"
fi
